apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: product-api
  namespace: product-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingressHostname }}
    http:
      paths:
      - backend:
          serviceName: product-api-stable
          servicePort: http
        path: /
  tls:
  - hosts:
    - {{ .Values.ingressHostname }}
    secretName: product-api-tls