apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  helmVersion: v3
  targetNamespace: cert-manager
  releaseName: cert-manager
  wait: true
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: "v1.0.1"
  values:
    installCRDs: false
