apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: ingress-nginx
spec:
  helmVersion: v3
  targetNamespace: ingress-nginx
  releaseName: flagger
  wait: true
  test:
    enable: true
  chart:
    repository: https://flagger.app
    name: flagger
    version: "1.1.0"
  values:
    meshProvider: nginx
    prometheus:
      install: true