# kubeapps behaves weird if you don't install it into default namespace
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: default
spec:
  helmVersion: v3
  targetNamespace: default
  releaseName: kubeapps
  wait: true
  test:
    enable: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: kubeapps
    version: "3.9.2"
  values:
    useHelm3: true