apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: product-api
  namespace: product-api
spec:
  commonName: product-api.lab.home
  dnsNames:
  - product-api.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: product-api-tls