apiVersion: v1
kind: Namespace
metadata:
  name: contour
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  helmVersion: v3
  targetNamespace: contour
  releaseName: contour
  wait: true
  test:
    enable: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: contour
    version: "1.2.0"
  values:
    envoy:
      service:
        type: ClusterIP
        externalTrafficPolicy: ""
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet