apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  helmVersion: v3
  targetNamespace: harbor
  releaseName: harbor
  wait: true
  test:
    enable: true
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: "1.4.1"
  values:
    database:
      maxOpenConns: -1
    clair:
      enabled: false
    chartmuseum:
      enabled: false
    trivy:
      enabled: true
    notary:
      enabled: false
    expose:
      type: ingress
      tls:
        enabled: true
        secretName: harbor
      ingress:
        hosts:
          core: harbor.lab.home
    externalURL: "https://harbor.lab.home"
    persistence:
      resourcePolicy: "" # Delete PVCs after helm uninstall
      persistentVolumeClaim:
        registry:
          size: 100Gi