#@ load("@ytt:data", "data")
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: concourse
  namespace: concourse
spec:
  helmVersion: v3
  targetNamespace: concourse
  releaseName: concourse
  wait: true
  test:
    enable: true
  chart:
    repository: https://concourse-charts.storage.googleapis.com/
    name: concourse
    version: "11.4.0"
  values:
    concourse:
      web:
        externalUrl: #@ "https://" + data.values.concourse_hostname
        kubernetes:
          keepNamespaces: false
    web:
      ingress:
        enabled: true
        hosts:
          - #@ data.values.concourse_hostname
        tls:
          - secretName: concourse-web-tls
            hosts:
              - #@ data.values.concourse_hostname