apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
spec:
  commonName: spring-petclinic.lab.home
  dnsNames:
  - spring-petclinic.lab.home
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: spring-petclinic-tls