---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: harbor.lab.home/library/spring-petclinic@sha256:3fe175f295c888f8d717b529460280f359abfdfad1e84e0b992cdd4c613a979b
        ports:
        - containerPort: 8080
        env:
        - name: WAVEFRONT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: wavefront_api_token
        - name: WAVEFRONT_URL
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: wavefront_url
        - name: spring_profiles_active
          value: mysql
        - name: MYSQL_URL
          value: "jdbc:mysql://mysql.mysql.svc.cluster.local/petclinic"