apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
spec:
  helmVersion: v3
  targetNamespace: spring-petclinic
  releaseName: spring-petclinic
  wait: true
  test:
    enable: true
  chart:
    git: https://github.com/techgnosis/tanzu-gitops.git
    ref: master
    path: manifests/spring-petclinic-helm
  values:
    ingressHostname: spring-petclinic.lab.home