resources:
- name: product-api
  type: git
  source:
    uri: https://github.com/techgnosis/product-api.git
    branch: demo
- name: tanzu-gitops
  type: git
  source:
    uri: https://github.com/techgnosis/tanzu-gitops.git
    branch: master
- name: product-api-image
  type: docker-image
  source:
    repository: harbor.lab.home/library/product-api
    tag: latest
    ca_certs:
    - domain: harbor.lab.home
      cert: |
        ((tanzu-gitops.ca_cert))
- name: concourse-helper
  type: docker-image
  source:
    repository: harbor.lab.home/library/concourse-helper
    tag: 1
    ca_certs:
    - domain: harbor.lab.home
      cert: |
        ((tanzu-gitops.ca_cert))

  


jobs:
- name: Build with TBS
  public: true
  serial: true
  plan:
  - get: product-api
    trigger: true
  - get: concourse-helper
  - get: tanzu-gitops
  - task: handoff to TBS
    image: concourse-helper
    file: tanzu-gitops/concourse/tasks/build-product-api-image/build-product-api-image.yml
    params:
      tkgicluster: tbs
      tkgiapi: ((tanzu-gitops.tkgi_url))
      tkgiuser: ((tanzu-gitops.tkgi_user))
      tkgipassword: ((tanzu-gitops.tkgi_password))



- name: Deploy to cluster
  public: true
  serial: true
  plan:
    - get: product-api-image
      trigger: true
    - get: tanzu-gitops
    - get: concourse-helper
    - task: handoff to argo rollouts
      file: tanzu-gitops/concourse/tasks/deploy-product-api-image/deploy-product-api-image.yml
      image: concourse-helper
      params:
        tkgicluster: product-api
        tkgiapi: ((tanzu-gitops.tkgi_url))
        tkgiuser: ((tanzu-gitops.tkgi_user))
        tkgipassword: ((tanzu-gitops.tkgi_password))


